name: Build App
on:
  push:
    branches: [ master ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@main
        - name: Set up JDK 1.8
          uses: actions/setup-java@main
          with:
            distribution: 'adopt'
            java-version: 8
        - name: Setup Android SDK
          uses: android-actions/setup-android@main
        - name: Setup execution rights for gradlew script
          run: chmod +x gradlew
          shell: bash
        - name: Build
          run: ./gradlew build